import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface GenerateProfileRequest {
  prompt: string;
  styleReferenceBase64?: string;
  protagonistReferenceBase64?: string;
  protagonistName?: string;
  customApiKey?: string;
}

interface Part {
  inlineData?: { data: string; mimeType: string };
  text?: string;
}

/**
 * Generate a character profile image (1:1 headshot)
 *
 * Features:
 * - Optional style reference image for consistent art style
 * - Optional protagonist reference for familial resemblance or style consistency
 */
export async function POST(request: NextRequest) {
  try {
    let body: GenerateProfileRequest;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error("[generate-profile] Failed to parse request body:", parseError);
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const {
      prompt,
      styleReferenceBase64,
      protagonistReferenceBase64,
      protagonistName,
      customApiKey,
    } = body;

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "Prompt is required and must be a string" },
        { status: 400 }
      );
    }

    const apiKey = customApiKey || process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });
    const parts: Part[] = [];

    // Add style reference if provided (first image)
    if (styleReferenceBase64) {
      parts.push({
        inlineData: {
          data: styleReferenceBase64,
          mimeType: "image/png",
        },
      });
      parts.push({
        text: "Use the above image strictly as a Style Reference for face and hair details (stroke, shading, lighting, eye design). Do NOT copy the clothing or character design from the reference.",
      });
    }

    // Add protagonist reference if provided (for familial resemblance)
    if (protagonistReferenceBase64) {
      parts.push({
        inlineData: {
          data: protagonistReferenceBase64,
          mimeType: "image/png",
        },
      });
      const referenceInstruction = protagonistName
        ? `Character relationship context: Use the provided image of "${protagonistName}" as a visual reference for familial resemblance or style consistency where appropriate, but generate the distinct character described in the text prompt.`
        : "Use the provided character image as a reference for style consistency and familial resemblance where appropriate, but generate the distinct character described in the prompt.";
      parts.push({ text: referenceInstruction });
    }

    // Add the main prompt
    parts.push({ text: prompt });

    console.log("[generate-profile] Model: gemini-3-pro-image-preview");
    console.log("[generate-profile] Has style reference:", !!styleReferenceBase64);
    console.log("[generate-profile] Has protagonist reference:", !!protagonistReferenceBase64);

    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "1:1", // Square for profile/headshot
          imageSize: "1K", // 1K for faster generation
        },
      },
    });

    // Extract image from response
    for (const candidate of response.candidates || []) {
      if (!candidate.content?.parts) continue;
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return NextResponse.json({ imageBase64: part.inlineData.data });
        }
      }
    }

    console.error("[generate-profile] No image in response");
    throw new Error("No profile image was generated by the model.");
  } catch (error: unknown) {
    console.error("Error in generate_character_sheet/generate-profile API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        {
          error:
            "The AI model is currently overloaded. Please try again in a few moments.",
        },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}