import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface GenerateImageRequest {
  prompt: string;
  referenceImage?: string; // Base64 manga panel to colorize
  assetImages?: string[]; // Base64 character/background sheets for color consistency
  aspectRatio?: "1:1" | "16:9" | "9:16";
  customApiKey?: string;
}

const IMAGE_PROMPT_SUFFIX = "No vfx or visual effects, no dust particles";

function appendSuffix(prompt: string): string {
  if (!prompt) return prompt;
  const trimmed = prompt.trim();
  const suffixLower = IMAGE_PROMPT_SUFFIX.toLowerCase();
  const promptLower = trimmed.toLowerCase();

  if (promptLower.endsWith(suffixLower) || promptLower.endsWith(suffixLower + '.')) {
    return trimmed;
  }

  const connector = (trimmed.endsWith('.') || trimmed.endsWith(',')) ? " " : ", ";
  return `${trimmed}${connector}${IMAGE_PROMPT_SUFFIX}`;
}

export async function POST(request: NextRequest) {
  try {
    let body: GenerateImageRequest;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error("[storyboard-editor/generate-image] Failed to parse request body:", parseError);
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const {
      prompt,
      referenceImage,
      assetImages = [],
      aspectRatio = "16:9",
      customApiKey
    } = body;

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "Prompt is required and must be a string" },
        { status: 400 }
      );
    }

    // Use custom API key if provided, otherwise fall back to environment variable
    const apiKey = customApiKey || process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });
    const finalPrompt = appendSuffix(prompt);

    const parts: any[] = [];

    const systemInstruction = `
You are an expert anime production artist.
GOAL: Generate a clean, high-quality anime screenshot (GENGA style).

MANDATORY CLEANUP RULES:
1. **DELETE ALL TEXT**: Strictly remove any and all speech bubbles, narration boxes, on-screen text, and typography.
2. **DELETE SFX**: Remove all sound effect text (onomatopoeia).
3. **DELETE BORDERS**: Remove all manga panel borders and frame lines.
4. **COLOR CONSISTENCY**: Use the provided "Asset Reference" images for exact hair, skin, and outfit colors.
5. **COMPOSITION**: If a manga panel is provided, maintain the EXACT pose and camera angle, but convert the art style into a polished anime frame.

Output ONLY the clean visual frame.
Current Scene: ${finalPrompt}
`;

    // Add asset context images
    assetImages.forEach((data, i) => {
      parts.push({ text: `Asset Reference ${i + 1} (COLOR SOURCE):` });
      parts.push({ inlineData: { data, mimeType: 'image/jpeg' } });
    });

    // Add reference manga panel
    if (referenceImage) {
      parts.push({ text: "Source Manga Panel (CONVERT TO CLEAN ANIME FRAME):" });
      parts.push({ inlineData: { data: referenceImage, mimeType: 'image/jpeg' } });
    }

    parts.push({ text: systemInstruction });

    console.log("[storyboard-editor/generate-image] Model: gemini-2.5-flash-image");
    console.log("[storyboard-editor/generate-image] Aspect ratio:", aspectRatio);

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
        },
      },
    });

    // Extract image from response
    for (const candidate of response.candidates || []) {
      if (!candidate.content?.parts) continue;
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return NextResponse.json({ imageBase64: part.inlineData.data });
        }
      }
    }

    console.error("[storyboard-editor/generate-image] No image in response");
    throw new Error("No image was generated by the model.");
  } catch (error: unknown) {
    console.error("Error in storyboard-editor/generate-image API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        {
          error:
            "The AI model is currently overloaded. Please try again in a few moments.",
        },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}
