import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface GenerateImageRequest {
  prompt: string;
  referenceImageBase64?: string; // Optional reference image for guided generation
  aspectRatio?: "1:1" | "16:9" | "9:16" | "4:3" | "3:4";
  customApiKey?: string;
}

const IMAGE_PROMPT_SUFFIX = "No vfx or visual effects, no dust particles";

function appendSuffix(prompt: string): string {
  if (!prompt) return prompt;
  const trimmed = prompt.trim();
  if (trimmed.toLowerCase().endsWith(IMAGE_PROMPT_SUFFIX.toLowerCase())) {
    return trimmed;
  }
  const connector = trimmed.endsWith(".") || trimmed.endsWith(",") ? " " : ", ";
  return `${trimmed}${connector}${IMAGE_PROMPT_SUFFIX}`;
}

export async function POST(request: NextRequest) {
  try {
    let body: GenerateImageRequest;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error("[generate-prop-image] Failed to parse request body:", parseError);
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const { prompt, referenceImageBase64, aspectRatio = "16:9", customApiKey } = body;

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "Prompt is required and must be a string" },
        { status: 400 }
      );
    }

    // Use custom API key if provided, otherwise fall back to environment variable
    const apiKey = customApiKey || process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });

    // Prepare prompt with suffix
    const finalPrompt = appendSuffix(prompt);

    console.log("[generate-prop-image] Model: gemini-3-pro-image-preview");
    console.log("[generate-prop-image] Aspect ratio:", aspectRatio);
    console.log("[generate-prop-image] Has reference image:", !!referenceImageBase64);

    // Build content parts
    const parts: Array<{ text: string } | { inlineData: { data: string; mimeType: string } }> = [];

    // Add reference image if provided
    if (referenceImageBase64) {
      // Remove data:image/...;base64, prefix if exists
      const base64Data = referenceImageBase64.includes("base64,")
        ? referenceImageBase64.split("base64,")[1]
        : referenceImageBase64;

      parts.push({
        inlineData: {
          data: base64Data,
          mimeType: "image/png",
        },
      });
    }

    // Add text prompt
    parts.push({ text: finalPrompt });

    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
          imageSize: "2K",
        },
      },
    });

    // Extract image from response
    for (const candidate of response.candidates || []) {
      if (!candidate.content?.parts) continue;
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return NextResponse.json({ imageBase64: part.inlineData.data });
        }
      }
    }

    console.error(
      "[generate-prop-image] No image in response. Full response:",
      JSON.stringify(response, null, 2)
    );
    throw new Error("No image was generated by the model.");
  } catch (error: unknown) {
    console.error("Error in generate_prop_sheet/generate-image API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        {
          error:
            "The AI model is currently overloaded. Please try again in a few moments.",
        },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}
