import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface GenerateMasterSheetRequest {
  prompt: string;
  profileImageBase64: string;
  styleReferenceBase64?: string;
  customApiKey?: string;
}

interface Part {
  inlineData?: { data: string; mimeType: string };
  text?: string;
}

/**
 * Generate a character master sheet (16:9, 4 views)
 *
 * Required: Profile image as reference for facial consistency
 * Optional: Style reference for art style
 *
 * Output: 16:9 character sheet with:
 * - Full body front view
 * - Face closeup front view
 * - Face closeup side view
 * - Face closeup 3/4 view (or back view)
 */
export async function POST(request: NextRequest) {
  try {
    let body: GenerateMasterSheetRequest;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error("[generate-master-sheet] Failed to parse request body:", parseError);
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const { prompt, profileImageBase64, styleReferenceBase64, customApiKey } = body;

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "Prompt is required and must be a string" },
        { status: 400 }
      );
    }

    if (!profileImageBase64 || typeof profileImageBase64 !== "string") {
      return NextResponse.json(
        { error: "profileImageBase64 is required for master sheet generation" },
        { status: 400 }
      );
    }

    const apiKey = customApiKey || process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });
    const parts: Part[] = [];

    // Add profile image as the primary reference (first image)
    parts.push({
      inlineData: {
        data: profileImageBase64,
        mimeType: "image/png",
      },
    });
    parts.push({
      text: "Use the provided profile image as the PRIMARY visual reference for the character design. Maintain exact consistency with the hair style, hair color, eye color, and facial features shown.",
    });

    // Add style reference if provided
    if (styleReferenceBase64) {
      parts.push({
        inlineData: {
          data: styleReferenceBase64,
          mimeType: "image/png",
        },
      });
      parts.push({
        text: "Use the above image as a Style Reference for the art style (stroke, shading, lighting). Do NOT copy the character design from this reference.",
      });
    }

    // Build the master sheet prompt
    const masterSheetPrompt = `
Create a white background character sheet for the character shown in the reference image.

The character sheet MUST contain these 4 views arranged in a 16:9 layout:
1. Full body front view (showing complete outfit and pose)
2. Face closeup front view (detailed facial features)
3. Face closeup side view (profile view of face)
4. Face closeup 3/4 view (extreme low angle or back of head)

CRITICAL REQUIREMENTS:
- Maintain EXACT consistency with the reference image for: hair style, hair color, eye color, facial features
- White or clean neutral background
- Clear separation between views
- High detail on facial features in closeup views

Additional character details: ${prompt}
    `.trim();

    parts.push({ text: masterSheetPrompt });


    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "16:9", // Wide for character sheet
          imageSize: "2K", // Higher resolution for detail
        },
      },
    });

    // Extract image from response
    for (const candidate of response.candidates || []) {
      if (!candidate.content?.parts) continue;
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return NextResponse.json({ imageBase64: part.inlineData.data });
        }
      }
    }

    console.error("[generate-master-sheet] No image in response");
    throw new Error("No master sheet was generated by the model.");
  } catch (error: unknown) {
    console.error("Error in generate_character_sheet/generate-master-sheet API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        {
          error:
            "The AI model is currently overloaded. Please try again in a few moments.",
        },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}