export const initialWebtoonContents = [
    {
        title: '웹툰 커리큘럼 1',
        subtitle: '개연성',
        title_en: 'Curriculum  01.',
        subtitle_en: 'Likelihood',
        title_jp: 'カリキュラム 01',
        subtitle_jp: '開放性',
        image: '/curriculum/curri_webtoon_book.png',
        image_en: '/curriculum/curri_webtoon_book_en.png',
        image_jp: '/curriculum/curri_webtoon_book_jp.png',
        file_src: 'webtoon_001.mp4',
        file_src_en: 'webtoon_english_001.mp4',
        file_src_jp: 'webtoon_japan_001.mp4',
        videoUrl: 'https://www.youtube.com/embed/4fnBIsX9_Dw?si=faCKtGDgbjS2jmn7',
        video: <iframe key={1} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/4fnBIsX9_Dw?si=faCKtGDgbjS2jmn7" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹툰 커리큘럼 2',
        subtitle: '상업성',
        title_en: 'Curriculum  02.',
        subtitle_en: 'Marketability',
        title_jp: 'カリキュラム 02',
        subtitle_jp: '市場性',
        image: '/curriculum/curri_webtoon_book.png',
        image_en: '/curriculum/curri_webtoon_book_en.png',
        image_jp: '/curriculum/curri_webtoon_book_jp.png',
        file_src: 'webtoon_002.mp4',
        file_src_en: 'webtoon_english_002.mp4',
        file_src_jp: 'webtoon_japan_002.mp4',
        videoUrl: 'https://www.youtube.com/embed/bqU8IUq1gZo?si=HoQ7JxrFKlvZV19N',
        video: <iframe key={2} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/bqU8IUq1gZo?si=HoQ7JxrFKlvZV19N" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹툰 커리큘럼 3',
        subtitle: '연속성',
        title_en: 'Curriculum  03.',
        subtitle_en: 'Continuity',
        title_jp: 'カリキュラム 03',
        subtitle_jp: '連続性',
        image: '/curriculum/curri_webtoon_book.png',
        image_en: '/curriculum/curri_webtoon_book_en.png',
        image_jp: '/curriculum/curri_webtoon_book_jp.png',
        file_src: 'webtoon_003.mp4',
        file_src_en: 'webtoon_english_003.mp4',
        file_src_jp: 'webtoon_japan_003.mp4',
        videoUrl: 'https://www.youtube.com/embed/9rakUYd2r7E?si=qwAxjQrW0tI3njL3',
        video: <iframe key={3} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/9rakUYd2r7E?si=qwAxjQrW0tI3njL3" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹툰 커리큘럼 4',
        subtitle: '시나리오 (콘티)',
        title_en: 'Curriculum  04.',
        subtitle_en: 'Scenario (Storyboard)',
        title_jp: 'カリキュラム 04',
        subtitle_jp: 'シナリオ (コンティ)',
        image: '/curriculum/curri_webtoon_book.png',
        image_en: '/curriculum/curri_webtoon_book_en.png',
        image_jp: '/curriculum/curri_webtoon_book_jp.png',
        file_src: 'webtoon_004.mp4',
        file_src_en: 'webtoon_english_004.mp4',
        file_src_jp: 'webtoon_japan_004.mp4',
        videoUrl: 'https://www.youtube.com/embed/OuhnJ9qZwLY?si=l_B-yRaEZaLhCwEC',
        video: <iframe key={4} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/OuhnJ9qZwLY?si=l_B-yRaEZaLhCwEC" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹툰 커리큘럼 5',
        subtitle: '컷 작업',
        title_en: 'Curriculum  05.',
        subtitle_en: 'Editing',
        title_jp: 'カリキュラム 05',
        subtitle_jp: 'カット作業',
        image: '/curriculum/curri_webtoon_book.png',
        image_en: '/curriculum/curri_webtoon_book_en.png',
        image_jp: '/curriculum/curri_webtoon_book_jp.png',
        file_src: 'webtoon_005.mp4',
        file_src_en: 'webtoon_english_005.mp4',
        file_src_jp: 'webtoon_japan_005.mp4',
        videoUrl: 'https://www.youtube.com/embed/dHIFPNZWqLc?si=tu0EgVAENJ-khnLU',
        video: <iframe key={5} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/dHIFPNZWqLc?si=tu0EgVAENJ-khnLU" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹툰 커리큘럼 6',
        subtitle: '인물 및 말풍선',
        title_en: 'Curriculum  06.',
        subtitle_en: 'Character & Speech Bubble',
        title_jp: 'カリキュラム 06',
        subtitle_jp: '人物と吹き出し',
        image: '/curriculum/curri_webtoon_book.png',
        image_en: '/curriculum/curri_webtoon_book_en.png',
        image_jp: '/curriculum/curri_webtoon_book_jp.png',
        file_src: 'webtoon_006.mp4',
        file_src_en: 'webtoon_english_006.mp4',
        file_src_jp: 'webtoon_japan_006.mp4',
        videoUrl: 'https://www.youtube.com/embed/6xMllO-8CpM?si=nNuBgInd-xiAIup-',
        video: <iframe key={6} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/6xMllO-8CpM?si=nNuBgInd-xiAIup-" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
]


export const initialWebnovelContents = [
    {
        title: '웹소설 커리큘럼 1',
        subtitle: '웹소설 소개',
        title_en: 'Curriculum  01.',
        subtitle_en: 'Introduction',
        title_jp: 'ウェブ小説 カリキュラム 01',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_001.mp4',
        file_src_en: 'webnovel_english_001.mp4',
        file_src_jp: 'webnovel_japan_001.mp4',
        videoUrl: 'https://www.youtube.com/embed/Mzij9X5uDTY?si=lU9Rgl3p1SsSXoLm',
        video: <iframe key={1} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/Mzij9X5uDTY?si=lU9Rgl3p1SsSXoLm" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 2',
        subtitle: '소재 선정',
        title_en: 'Curriculum  02.',
        subtitle_en: 'Subject Selection',
        title_jp: 'ウェブ小説 カリキュラム 02',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_002.mp4',
        file_src_en: 'webnovel_english_002.mp4',
        file_src_jp: 'webnovel_japan_002.mp4',
        videoUrl: 'https://www.youtube.com/embed/uzQ7ebnUVns?si=2dosrLLuNjkpQaL5',
        video: <iframe key={2} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/uzQ7ebnUVns?si=2dosrLLuNjkpQaL5" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 3',
        subtitle: '프롤로그의 공식',
        title_en: 'Curriculum  03.',
        subtitle_en: 'Prologue',
        title_jp: 'ウェブ小説 カリキュラム 03',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_003.mp4',
        file_src_en: 'webnovel_english_003.mp4',
        file_src_jp: 'webnovel_japan_003.mp4',
        videoUrl: 'https://www.youtube.com/embed/C0IjxeDn01A?si=3magNphFLhyG1QsG',
        video: <iframe key={3} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/C0IjxeDn01A?si=3magNphFLhyG1QsG" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 4',
        subtitle: '플롯 구성',
        title_en: 'Curriculum  04.',
        subtitle_en: 'Plot Structure',
        title_jp: 'ウェブ小説 カリキュラム 04',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_004.mp4',
        file_src_jp: 'webnovel_japan_004.mp4',
        videoUrl: 'https://www.youtube.com/embed/yMtN4sNHe9E?si=6T4Sjbuf_wIYjr2Z',
        video: <iframe key={4} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/yMtN4sNHe9E?si=6T4Sjbuf_wIYjr2Z" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 5',
        subtitle: '인물 만들기',
        title_en: 'Curriculum  05.',
        subtitle_en: 'Character Creation',
        title_jp: 'ウェブ小説 カリキュラム 05',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_005.mp4',
        file_src_en: 'webnovel_english_005.mp4',
        file_src_jp: 'webnovel_japan_005.mp4',
        videoUrl: 'https://www.youtube.com/embed/VO5eKFQ50vs?si=YZ0UTqMNW3uNwVHp',
        video: <iframe key={5} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/VO5eKFQ50vs?si=YZ0UTqMNW3uNwVHp" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 6',
        subtitle: '기타',
        title_en: 'Curriculum  06.',
        subtitle_en: 'Miscellaneous',
        title_jp: 'ウェブ小説 カリキュラム 06',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_006.mp4',
        file_src_en: 'webnovel_english_006.mp4',
        file_src_jp: 'webnovel_japan_006.mp4',
        videoUrl: 'https://www.youtube.com/embed/rFygTsA83s0?si=WX0uV6KOeLvwEjRJ',
        video: <iframe key={6} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/rFygTsA83s0?si=WX0uV6KOeLvwEjRJ" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
]