export const initialWebnovelContents = [
    {
        title: '웹소설 커리큘럼 1',
        subtitle: '웹소설 소개',
        title_en: 'Curriculum  01.',
        subtitle_en: 'Introduction',
        title_jp: 'ウェブ小説 カリキュラム 01',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_001.mp4',
        file_src_en: 'webnovel_english_001.mp4',
        file_src_jp: 'webnovel_japan_001.mp4',
        videoUrl: 'https://www.youtube.com/embed/Mzij9X5uDTY?si=lU9Rgl3p1SsSXoLm',
        video: <iframe key={1} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/Mzij9X5uDTY?si=lU9Rgl3p1SsSXoLm" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 2',
        subtitle: '소재 선정',
        title_en: 'Curriculum  02.',
        subtitle_en: 'Subject Selection',
        title_jp: 'ウェブ小説 カリキュラム 02',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_002.mp4',
        file_src_en: 'webnovel_english_002.mp4',
        file_src_jp: 'webnovel_japan_002.mp4',
        videoUrl: 'https://www.youtube.com/embed/uzQ7ebnUVns?si=2dosrLLuNjkpQaL5',
        video: <iframe key={2} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/uzQ7ebnUVns?si=2dosrLLuNjkpQaL5" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 3',
        subtitle: '프롤로그의 공식',
        title_en: 'Curriculum  03.',
        subtitle_en: 'Prologue',
        title_jp: 'ウェブ小説 カリキュラム 03',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_003.mp4',
        file_src_en: 'webnovel_english_003.mp4',
        file_src_jp: 'webnovel_japan_003.mp4',
        videoUrl: 'https://www.youtube.com/embed/C0IjxeDn01A?si=3magNphFLhyG1QsG',
        video: <iframe key={3} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/C0IjxeDn01A?si=3magNphFLhyG1QsG" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 4',
        subtitle: '플롯 구성',
        title_en: 'Curriculum  04.',
        subtitle_en: 'Plot Structure',
        title_jp: 'ウェブ小説 カリキュラム 04',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_004.mp4',
        file_src_jp: 'webnovel_japan_004.mp4',
        videoUrl: 'https://www.youtube.com/embed/yMtN4sNHe9E?si=6T4Sjbuf_wIYjr2Z',
        video: <iframe key={4} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/yMtN4sNHe9E?si=6T4Sjbuf_wIYjr2Z" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 5',
        subtitle: '인물 만들기',
        title_en: 'Curriculum  05.',
        subtitle_en: 'Character Creation',
        title_jp: 'ウェブ小説 カリキュラム 05',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_005.mp4',
        file_src_en: 'webnovel_english_005.mp4',
        file_src_jp: 'webnovel_japan_005.mp4',
        videoUrl: 'https://www.youtube.com/embed/VO5eKFQ50vs?si=YZ0UTqMNW3uNwVHp',
        video: <iframe key={5} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/VO5eKFQ50vs?si=YZ0UTqMNW3uNwVHp" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
    {
        title: '웹소설 커리큘럼 6',
        subtitle: '기타',
        title_en: 'Curriculum  06.',
        subtitle_en: 'Miscellaneous',
        title_jp: 'ウェブ小説 カリキュラム 06',
        subtitle_jp: '',
        image: '/curriculum/curri_webnovel_book.png',
        image_en: '/curriculum/curri_webnovel_book_en.png',
        image_jp: '/curriculum/curri_webnovel_book_jp.png',
        file_src: 'webnovel_006.mp4',
        file_src_en: 'webnovel_english_006.mp4',
        file_src_jp: 'webnovel_japan_006.mp4',
        videoUrl: 'https://www.youtube.com/embed/rFygTsA83s0?si=WX0uV6KOeLvwEjRJ',
        video: <iframe key={6} className="w-[320px] md:w-[560px] h-[180px] md:h-[315px]" src="https://www.youtube.com/embed/rFygTsA83s0?si=WX0uV6KOeLvwEjRJ" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
    },
]