import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface EditProfileRequest {
  originalImageBase64: string;
  maskBase64?: string; // Optional - not used by current implementation
  editPrompt: string;
  styleReferenceBase64?: string;
  customApiKey?: string;
}

interface Part {
  inlineData?: { data: string; mimeType: string };
  text?: string;
}

/**
 * Edit a character profile image using AI
 *
 * Takes the original image and an edit prompt describing what to change.
 * Uses Gemini's image generation to create an edited version while preserving the character.
 */
export async function POST(request: NextRequest) {
  try {
    let body: EditProfileRequest;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error("[edit-profile] Failed to parse request body:", parseError);
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const {
      originalImageBase64,
      editPrompt,
      styleReferenceBase64,
      customApiKey,
    } = body;

    if (!originalImageBase64 || typeof originalImageBase64 !== "string") {
      return NextResponse.json(
        { error: "originalImageBase64 is required" },
        { status: 400 }
      );
    }

    if (!editPrompt || typeof editPrompt !== "string") {
      return NextResponse.json(
        { error: "editPrompt is required" },
        { status: 400 }
      );
    }

    const apiKey = customApiKey || process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });
    const parts: Part[] = [];

    // Add the original image
    parts.push({
      inlineData: {
        data: originalImageBase64,
        mimeType: "image/png",
      },
    });

    // Add style reference if provided
    if (styleReferenceBase64) {
      parts.push({
        inlineData: {
          data: styleReferenceBase64,
          mimeType: "image/png",
        },
      });
    }

    // Construct the edit prompt
    const systemPrompt = `[IMAGE EDITING TASK]

You are an expert digital artist performing precise image editing.

INPUT: A character portrait that needs a specific edit.
${styleReferenceBase64 ? "STYLE REFERENCE: Match the art style of the second image." : ""}

EDITING INSTRUCTIONS:
${editPrompt}

CRITICAL RULES:
1. Make ONLY the requested change - preserve everything else exactly as it appears
2. Keep the same character identity, pose, and composition
3. Maintain the same art style, lighting, and quality throughout
4. The result should look natural and cohesive
5. Do NOT add any extra elements, watermarks, or borders

Generate the edited image now.`;

    parts.push({ text: systemPrompt });


    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K",
        },
      },
    });

    // Extract image from response
    for (const candidate of response.candidates || []) {
      if (!candidate.content?.parts) continue;
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return NextResponse.json({ imageBase64: part.inlineData.data });
        }
      }
    }

    console.error("[edit-profile] No image in response");
    throw new Error("No edited image was generated by the model.");
  } catch (error: unknown) {
    console.error("Error in generate_character_sheet/edit-profile API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        {
          error:
            "The AI model is currently overloaded. Please try again in a few moments.",
        },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}