import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface ImageRemixRequest {
  referenceImageBase64: string;
  prompt: string;
  aspectRatio?: "16:9" | "9:16" | "1:1";
  customApiKey?: string;
}

export async function POST(request: NextRequest) {
  try {
    let body: ImageRemixRequest;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const { referenceImageBase64, prompt, aspectRatio = "16:9", customApiKey } = body;

    if (!referenceImageBase64 || typeof referenceImageBase64 !== "string") {
      return NextResponse.json(
        { error: "referenceImageBase64 is required and must be a string" },
        { status: 400 }
      );
    }

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "prompt is required and must be a string" },
        { status: 400 }
      );
    }

    const apiKey = customApiKey || process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });

    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: {
        parts: [
          {
            inlineData: {
              data: referenceImageBase64,
              mimeType: "image/jpeg",
            },
          },
          { text: prompt },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio,
          imageSize: "1K",
        },
      },
    });

    for (const candidate of response.candidates || []) {
      if (!candidate.content?.parts) continue;
      for (const part of candidate.content.parts) {
        if (part.inlineData?.data) {
          return NextResponse.json({ imageBase64: part.inlineData.data });
        }
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error: unknown) {
    console.error("Error in image/remix API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        { error: "The AI model is currently overloaded. Please try again in a few moments." },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}