import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface AnalyzeBackRequest {
  frontImageBase64: string;
  frontPrompt: string;
  style: string;
  frameworkGuide?: string;
  customApiKey?: string;
}

export async function POST(request: NextRequest) {
  try {
    let body: AnalyzeBackRequest;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const { frontImageBase64, frontPrompt, style, frameworkGuide, customApiKey } =
      body;

    if (!frontImageBase64 || !frontPrompt || !style) {
      return NextResponse.json(
        { error: "frontImageBase64, frontPrompt, and style are required" },
        { status: 400 }
      );
    }

    const apiKey = customApiKey || process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });

    let promptText = `
    You are an expert 3D environment artist.
    I will provide an image of the "Front View" of a scene and its description.
    Your task is to write a detailed image generation prompt for the "Back View" (180 degrees opposite).

    Front View Description: "${frontPrompt}"
    Art Style: "${style}"
  `;

    if (frameworkGuide) {
      promptText += `\n\n[FRAMEWORK GUIDE]\nThe user has provided the following specific framework/guide for generating the back view. You MUST strictly follow the logic, rules, and structure defined here:\n\n${frameworkGuide}\n\n[END OF FRAMEWORK GUIDE]\n`;
    }

    promptText += `
    Rules for Back View:
    1. Logical Consistency: If the front shows a palace entrance, the back should show the garden exit or the path leading away. If the front is a classroom blackboard, the back is the desks and rear windows.
    2. Visual Continuity: Mention the specific ground elements (e.g., "continuation of the cobblestone path with stone curbs", "matching grassy terrain") that need to connect at the edges.
    3. Lighting: Ensure the sun position and shadows match the reverse perspective.

    Output ONLY the raw prompt text for the Back View. Do not include "Here is the prompt" or quotes.
  `;

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: {
        parts: [
          {
            inlineData: {
              data: frontImageBase64,
              mimeType: "image/png",
            },
          },
          { text: promptText },
        ],
      },
    });

    const description = response.text?.trim() || "";

    if (!description) {
      throw new Error("No description was generated by the model.");
    }

    return NextResponse.json({ description });
  } catch (error: unknown) {
    console.error("Error in tools/bg-generator/analyze-back API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        {
          error:
            "The AI model is currently overloaded. Please try again in a few moments.",
        },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}
