import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

interface GenerateModeRequest {
  prompt: string;
  masterSheetImageBase64: string;
  modeName: string;
  modeDescription: string;
  styleReferenceBase64?: string;
  customApiKey?: string;
}

interface Part {
  inlineData?: { data: string; mimeType: string };
  text?: string;
}

/**
 * Generate a character mode variation (16:9)
 *
 * Required: Master sheet image as reference for facial consistency
 * Required: Mode name and description
 * Optional: Style reference for art style
 *
 * Output: 16:9 mode sheet showing the character in a different outfit, age, or situation
 * while maintaining facial consistency with the master sheet
 */
export async function POST(request: NextRequest) {
  try {
    let body: GenerateModeRequest;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error("[generate-mode] Failed to parse request body:", parseError);
      return NextResponse.json(
        { error: "Invalid or empty request body" },
        { status: 400 }
      );
    }

    const {
      prompt,
      masterSheetImageBase64,
      modeName,
      modeDescription,
      styleReferenceBase64,
      customApiKey,
    } = body;

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "Prompt is required and must be a string" },
        { status: 400 }
      );
    }

    if (!masterSheetImageBase64 || typeof masterSheetImageBase64 !== "string") {
      return NextResponse.json(
        { error: "masterSheetImageBase64 is required for mode generation" },
        { status: 400 }
      );
    }

    if (!modeName || !modeDescription) {
      return NextResponse.json(
        { error: "modeName and modeDescription are required" },
        { status: 400 }
      );
    }

    const apiKey = customApiKey || process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });
    const parts: Part[] = [];

    // Add master sheet as the primary reference (first image)
    parts.push({
      inlineData: {
        data: masterSheetImageBase64,
        mimeType: "image/png",
      },
    });
    parts.push({
      text: "Use the provided master sheet as the PRIMARY reference for the character. Maintain EXACT consistency with the facial features, hair style, and hair color shown. This is the character's canonical appearance.",
    });

    // Add style reference if provided
    if (styleReferenceBase64) {
      parts.push({
        inlineData: {
          data: styleReferenceBase64,
          mimeType: "image/png",
        },
      });
      parts.push({
        text: "Use the above image as a Style Reference for the art style (stroke, shading, lighting). Do NOT copy the character design from this reference.",
      });
    }

    // Build the mode prompt
    const modePrompt = `
Create an alternate character design sheet for mode: "${modeName}"

Mode Description: ${modeDescription}

REQUIREMENTS:
1. MAINTAIN the character's facial features from the reference (hair, eyes, face shape)
2. Show the character in this new mode/outfit/situation
3. Include: Full body view + Close-up view
4. White or clean neutral background

Character Details: ${prompt}

This is a variation of the character, NOT a different character. The face must be recognizably the same person.
    `.trim();

    parts.push({ text: modePrompt });

    console.log("[generate-mode] Model: gemini-3-pro-image-preview");
    console.log("[generate-mode] Mode:", modeName);
    console.log("[generate-mode] Has style reference:", !!styleReferenceBase64);

    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "16:9", // Wide for mode sheet
          imageSize: "1K", // 1K for faster generation
        },
      },
    });

    // Extract image from response
    for (const candidate of response.candidates || []) {
      if (!candidate.content?.parts) continue;
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return NextResponse.json({ imageBase64: part.inlineData.data });
        }
      }
    }

    console.error("[generate-mode] No image in response");
    throw new Error("No mode image was generated by the model.");
  } catch (error: unknown) {
    console.error("Error in generate_character_sheet/generate-mode API:", error);

    const errorMessage = String(error);
    if (
      errorMessage.includes("503") ||
      errorMessage.includes("overloaded") ||
      errorMessage.includes("UNAVAILABLE")
    ) {
      return NextResponse.json(
        {
          error:
            "The AI model is currently overloaded. Please try again in a few moments.",
        },
        { status: 503 }
      );
    }

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}